In [1]:
### loading libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import os
from keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

Matplotlib created a temporary config/cache directory at /scratch/local/u6031121/10746/matplotlib-mxycmpcn because the default path (/home/jovyan/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [2]:
# Check available devices
devices = tf.config.list_physical_devices('GPU')

if len(devices) > 0:
    print("GPU is available")
    for device in devices:
        print("Device name:", device.name)
else:
    print("No GPU is available")

GPU is available
Device name: /physical_device:GPU:0


## Training data

In [3]:
############################ TRAINING DATA 


In [3]:
########### Training Data
#Set the directory paths for each type of CSV file
directory_path_channel1 = '/uufs/chpc.utah.edu/common/home/gompert-group4/projects/fluctCNN/DataSepFilesNov23/EnvFiles/trainEnv/'
directory_path_channel2 = '/uufs/chpc.utah.edu/common/home/gompert-group4/projects/fluctCNN/DataSepFilesNov23/FreqFiles/trainFreq/'

# Get lists of all CSV files in each directory
csv_files_channel1 = [file for file in os.listdir(directory_path_channel1) if file.endswith('.csv')]
csv_files_channel2 = [file for file in os.listdir(directory_path_channel2) if file.endswith('.csv')]

# Initialize lists to store matrices and labels
# Process each pair of CSV files
matrices_channel1 = []
matrices_channel2 = []
out_vec1 = []

for file_channel1, file_channel2 in zip(csv_files_channel1, csv_files_channel2):
    # Read CSV file for channel 1
    df_channel1 = pd.read_csv(os.path.join(directory_path_channel1, file_channel1), header=None, sep=',', dtype='float32')
    matrices_channel1.append(df_channel1)
    
    # Read CSV file for channel 2
    df_channel2 = pd.read_csv(os.path.join(directory_path_channel2, file_channel2), header=None, sep=',', dtype='float32')
    matrices_channel2.append(df_channel2)
    
    # Appending first eight letters to out_vec as labels (adjust as needed)
    label = file_channel2[:9]
    out_vec1.append(label)
# Stack matrices for each channel
input_arrays_channel1 = np.stack(matrices_channel1)
input_arrays_channel2 = np.stack(matrices_channel2)
# Reshape the input arrays
inDa_trn_channel1 = input_arrays_channel1.reshape((len(csv_files_channel1), 10, 10))
inDa_trn_channel2 = input_arrays_channel2.reshape((len(csv_files_channel2), 10, 10))


# Stack the channels
inDa_trn = np.stack([inDa_trn_channel1, inDa_trn_channel2], axis=-1)

# Print the shape of the final input array
print(inDa_trn.shape)

(15000, 10, 10, 2)


In [4]:
######### TRAINIG labels
labels_train =out_vec1
# converting string values to integer calsses
from sklearn.preprocessing import LabelEncoder
# Initialize a LabelEncoder object
label_encoder = LabelEncoder()
# Fit the LabelEncoder to your string list and transform the string values into integer classes
label_train_int = label_encoder.fit_transform(labels_train)
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
ouLa_trn =to_categorical(label_train_int)
ouLa_trn.shape
#print(ouLa_trn)
ouLa_trn.shape
labelint_train = label_train_int
labelint_train.shape

(15000,)

## Test data

In [5]:
############################ TEST DATA 
# changing directory to the data folder
########### Training Data
#Set the directory paths for each type of CSV file
directory_path_tst_channel1 = '/uufs/chpc.utah.edu/common/home/gompert-group4/projects/fluctCNN/DataSepFilesNov23/EnvFiles/testEnv/'
directory_path_tst_channel2 = '/uufs/chpc.utah.edu/common/home/gompert-group4/projects/fluctCNN/DataSepFilesNov23/FreqFiles/testFreq/'

# Get lists of all CSV files in each directory
csv_files_tst_channel1 = [file for file in os.listdir(directory_path_tst_channel1) if file.endswith('.csv')]
csv_files_tst_channel2 = [file for file in os.listdir(directory_path_tst_channel2) if file.endswith('.csv')]

# Initialize lists to store matrices and labels
# Process each pair of CSV files
matrices_tst_channel1 = []
matrices_tst_channel2 = []
out_vec2 = []

for file_channel1, file_channel2 in zip(csv_files_tst_channel1, csv_files_tst_channel2):
    # Read CSV file for channel 1
    df_tst_channel1 = pd.read_csv(os.path.join(directory_path_tst_channel1, file_channel1), header=None, sep=',', dtype='float32')
    matrices_tst_channel1.append(df_tst_channel1)
    
    # Read CSV file for channel 2
    df_tst_channel2 = pd.read_csv(os.path.join(directory_path_tst_channel2, file_channel2), header=None, sep=',', dtype='float32')
    matrices_tst_channel2.append(df_tst_channel2)
    
    # Appending first eight letters to out_vec as labels (adjust as needed)
    label = file_channel2[:9]
    out_vec2.append(label)
# Stack matrices for each channel
input_arrays_tst_channel1 = np.stack(matrices_tst_channel1)
input_arrays_tst_channel2 = np.stack(matrices_tst_channel2)
# Reshape the input arrays
inDa_tst_channel1 = input_arrays_tst_channel1.reshape((len(csv_files_tst_channel1), 10, 10))
inDa_tst_channel2 = input_arrays_tst_channel2.reshape((len(csv_files_tst_channel2), 10, 10))


# Stack the channels
inDa_tst = np.stack([inDa_tst_channel1, inDa_tst_channel2], axis=-1)

# Print the shape of the final input array
print(inDa_tst.shape)

(3000, 10, 10, 2)


In [6]:
######### TEST labels

labels_tst =out_vec2
# converting string values to integer calsses
from sklearn.preprocessing import LabelEncoder
# Initialize a LabelEncoder object
label_encoder = LabelEncoder()
# Fit the LabelEncoder to your string list and transform the string values into integer classes
label_tst_int = label_encoder.fit_transform(labels_tst)
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
ouLa_tst =to_categorical(label_tst_int)
ouLa_tst.shape
#print(ouLa_trn)
ouLa_tst.shape
labelint_tst = label_tst_int
labelint_tst


array([0, 0, 0, ..., 2, 2, 2])

## Validation data

#### Independent validation set generated afresh from the simulation script

In [7]:
############################ VALIDATION DATA 

# changing directory to the data folder
########### Training Data
#Set the directory paths for each type of CSV file
directory_path_val_channel1 = '/uufs/chpc.utah.edu/common/home/gompert-group4/projects/fluctCNN/DataSepFilesNov23/EnvFiles/valEnv/'
directory_path_val_channel2 = '/uufs/chpc.utah.edu/common/home/gompert-group4/projects/fluctCNN/DataSepFilesNov23/FreqFiles/valFreq/'

# Get lists of all CSV files in each directory
csv_files_val_channel1 = [file for file in os.listdir(directory_path_val_channel1) if file.endswith('.csv')]
csv_files_val_channel2 = [file for file in os.listdir(directory_path_val_channel2) if file.endswith('.csv')]

# Initialize lists to store matrices and labels
# Process each pair of CSV files
matrices_val_channel1 = []
matrices_val_channel2 = []
out_vec3 = []

for file_channel1, file_channel2 in zip(csv_files_val_channel1, csv_files_val_channel2):
    # Read CSV file for channel 1
    df_val_channel1 = pd.read_csv(os.path.join(directory_path_val_channel1, file_channel1), header=None, sep=',', dtype='float32')
    matrices_val_channel1.append(df_val_channel1)
    
    # Read CSV file for channel 2
    df_val_channel2 = pd.read_csv(os.path.join(directory_path_val_channel2, file_channel2), header=None, sep=',', dtype='float32')
    matrices_val_channel2.append(df_val_channel2)
    
    # Appending first eight letters to out_vec as labels (adjust as needed)
    label = file_channel2[:9]
    out_vec3.append(label)
# Stack matrices for each channel
input_arrays_val_channel1 = np.stack(matrices_val_channel1)
input_arrays_val_channel2 = np.stack(matrices_val_channel2)
# Reshape the input arrays
inDa_val_channel1 = input_arrays_val_channel1.reshape((len(csv_files_val_channel1), 10, 10))
inDa_val_channel2 = input_arrays_val_channel2.reshape((len(csv_files_val_channel2), 10, 10))


# Stack the channels
inDa_val = np.stack([inDa_val_channel1, inDa_val_channel2], axis=-1)

# Print the shape of the final input array
print(inDa_val.shape)

(3000, 10, 10, 2)


In [8]:
labels_val =out_vec3
# converting string values to integer calsses
from sklearn.preprocessing import LabelEncoder
# Initialize a LabelEncoder object
label_encoder = LabelEncoder()
# Fit the LabelEncoder to your string list and transform the string values into integer classes
label_val_int = label_encoder.fit_transform(labels_val)

In [9]:
######### VALIDATION labels
labels_val =out_vec3
# converting string values to integer calsses
from sklearn.preprocessing import LabelEncoder
# Initialize a LabelEncoder object
label_encoder = LabelEncoder()
# Fit the LabelEncoder to your string list and transform the string values into integer classes
label_val_int = label_encoder.fit_transform(labels_val)
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
ouLa_val =to_categorical(label_val_int)
ouLa_val.shape
#print(ouLa_trn)
ouLa_val.shape
labelint_val = label_val_int
labelint_val.shape

(3000,)

# # Machine Learning Algorithms

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn import datasets
from sklearn import metrics

In [13]:
# reshaping arrays for randomforest
X_flattened_train = inDa_trn.reshape((inDa_trn.shape[0], -1))
X_flattened_tst = inDa_tst.reshape((inDa_tst.shape[0], -1))
X_flattened_train.shape

(15000, 200)

In [15]:
# Step 3: Create and train the Random Forest model
rf_classifier = RandomForestClassifier(n_estimators=200, random_state=42, min_samples_split=4)
rf_classifier.fit(X_flattened_train, labelint_train)



RandomForestClassifier(min_samples_split=4, n_estimators=200, random_state=42)

In [16]:
y_pred = rf_classifier.predict(X_flattened_tst)
accuracy = accuracy_score(labelint_tst, y_pred)

In [18]:
print(f"Accuracy: {accuracy}")

print("Classification Report:\n", classification_report(labelint_tst, y_pred))

Accuracy: 0.638
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.90      0.94      1000
           1       0.48      0.49      0.49      1000
           2       0.49      0.52      0.51      1000

    accuracy                           0.64      3000
   macro avg       0.65      0.64      0.64      3000
weighted avg       0.65      0.64      0.64      3000



In [19]:
# Additionally, you can visualize the confusion matrix
conf_matrix = metrics.confusion_matrix(labelint_tst, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[896  56  48]
 [ 13 495 492]
 [  4 473 523]]


# XGBoost

In [73]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.1/297.1 MB 142.2 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [21]:
import xgboost as xgb

In [22]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [23]:
dtrain = xgb.DMatrix(X_flattened_train, label=labelint_train)
dtest = xgb.DMatrix(X_flattened_tst, label=labelint_tst)


In [24]:
# Set hyperparameters and train the model
params = {
    'objective': 'multi:softmax',  # Change to 'multi:softmax' for multiclass classification
    'eval_metric': 'logloss',         # Change based on your problem
    'max_depth': 3,
    'learning_rate': 0.1,
    'n_estimators': 100,
    'num_class':3
}


In [25]:
num_round = 100  # Number of boosting rounds

model = xgb.train(params, dtrain, num_round)

# Predictions on the test set
y_pred = model.predict(dtest)

/uufs/chpc.utah.edu/common/home/u6031121/.local/lib/python3.9/site-packages/xgboost/core.py:160: UserWarning: [14:37:55] WARNING: /workspace/src/learner.cc:742: 
Parameters: { "n_estimators" } are not used.

  warnings.warn(smsg, UserWarning)


In [26]:
y_pred_binary = [1 if pred > 0.5 else 0 for pred in y_pred]
accuracy = accuracy_score(labelint_tst, y_pred_binary)

print(f"Accuracy: {accuracy}")
print("Classification Report:\n", classification_report(labelint_tst, y_pred_binary))

Accuracy: 0.5523333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.75      0.79      1000
           1       0.43      0.91      0.58      1000
           2       0.00      0.00      0.00      1000

    accuracy                           0.55      3000
   macro avg       0.42      0.55      0.46      3000
weighted avg       0.42      0.55      0.46      3000



/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# CNN model

In [10]:
### CNN

model = keras.Sequential()
model.add(layers.Conv2D(64, kernel_size=(3, 3),strides=(1, 1),padding = "same", activation="relu", input_shape=(10,10,2)))
model.add(layers.Conv2D(128, kernel_size=(2, 2), strides=(1, 1), activation="relu"))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Dropout(0.2))
model.add(layers.Flatten())
model.add(layers.Dense(128, activation="relu"))
model.add(layers.Dropout(0.25))
model.add(layers.Dense(128, activation="relu"))
model.add(layers.Dropout(0.1))
model.add(layers.Dense(3, activation="softmax"))


optimizer = keras.optimizers.Adam(learning_rate=0.00005,
    beta_1=0.9,
    beta_2=0.99,
    #momentum=0.4,
    epsilon=1e-07,)

# Compile the model
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])

# Train the model
es = EarlyStopping(monitor='val_accuracy', patience=10, verbose=1)
history = model.fit(inDa_trn, ouLa_trn, batch_size=8, epochs=100,validation_data=(inDa_tst, ouLa_tst), callbacks=[es] )
print(history.history.keys())

# Evaluate the model on the test set
loss, accuracy = model.evaluate(inDa_val, ouLa_val)
# print("Test Loss:", loss)
# print("Test Accuracy:", accuracy)

# summarize history for accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

2023-12-18 16:00:13.423046: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-18 16:00:17.778953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9641 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:1c:00.0, compute capability: 7.5
2023-12-18 16:00:18.207434: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/100


2023-12-18 16:00:22.052007: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2023-12-18 16:00:26.086762: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2023-12-18 16:00:26.089059: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2023-12-18 16:00:26.089081: W tensorflow/stream_executor/gpu/asm_compiler.cc:77] Couldn't get ptxas version string: Internal: Couldn't invoke ptxas --version
2023-12-18 16:00:26.090437: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2023-12-18 16:00:26.090493: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Failed to launch ptxas
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.


1875/1875 [==============================] - 18s 2ms/step - loss: 1.1000 - accuracy: 0.3286 - val_loss: 1.0988 - val_accuracy: 0.3333
Epoch 2/100
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0991 - accuracy: 0.3345 - val_loss: 1.0988 - val_accuracy: 0.3333
Epoch 3/100
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0990 - accuracy: 0.3319 - val_loss: 1.0987 - val_accuracy: 0.3340
Epoch 4/100
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0990 - accuracy: 0.3357 - val_loss: 1.0985 - val_accuracy: 0.3377
Epoch 5/100
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0984 - accuracy: 0.3389 - val_loss: 1.0988 - val_accuracy: 0.3333
Epoch 6/100
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0981 - accuracy: 0.3424 - val_loss: 1.0987 - val_accuracy: 0.3313
Epoch 7/100
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0974 - accuracy: 0.3530 - val_loss: 1.0984 - val_accuracy: 0.3

In [11]:
# Making confusion matrix to find percentage of false positives an dfalse negatives
# use of test data to make predictions based on the model fitted
lable_predicted = model.predict(inDa_val)
lable_predicted_categories = np.argmax(lable_predicted, axis=1)
label_actual = np.argmax(ouLa_val, axis =1)

In [12]:
# calculaiton of confusion matrix\
cm = confusion_matrix(label_actual, lable_predicted_categories)
print(cm)
type(cm)


In [13]:
# iterating through numpy array to convert the values into percentage

oneD_total = np.sum(cm, axis =1)
cm_perc = cm/oneD_total[:,np.newaxis]
cm_perc

In [14]:
class_names = [0,1,2] # the vector defines three classes of selection types

In [16]:
# graphical visualization of the confusion matrix in the form of heatmap
plt.figure(figsize=(8,6))
sns.heatmap(cm_perc,  annot=True, cmap ='Blues', xticklabels =  class_names, yticklabels = class_names)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

In [60]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Calculate the sum of each 1D array (row)
row_sums = np.sum(array_2d, axis=1)
row_sums

array([ 6, 15, 24])